### ISSUE TITLE
Pixel Offset at Top and Left

### ISSUE THREAD

**Issue by McNugget6750** [Bodmer/TFT_ST7735#16]
While I was bringing up a battery monitor that worked fine with one display on my breadboard and then didn't with essentially the same display on my PCB, I came across the thread [here](https://forum.arduino.cc/index.php?topic=406501.0), which was extremely helpful!
I want to use your libraries because they are insanely fast! However, I don't get the same drawing reliability with your library, compared to the slow Adafruit lib:
![image](https://user-images.githubusercontent.com/12099353/66887449-e00fbb80-ef8f-11e9-8f86-f2b56dce07ff.png)
As you can see, the image looks fine using the Adafruit lib.

However, when I use yours, the entire screen is shifted by 1px horizontally and 2px vertically:
![image](https://user-images.githubusercontent.com/12099353/66887494-0d5c6980-ef90-11e9-8812-ea7f40ee1ac2.png)
Everything else seems to work just fine so I suspect there might be bug in one of the display driver components on your end.

Please let me know if and how I can help investigate since I am really impressed with the performance of this lib! Thanks for putting in all the work!

Cheers,
Timo

**Comment by Bodmer** [comment]
Different display boards use different offsets. The default display uses an offset.

Try using the [setup](https://github.com/Bodmer/TFT_ST7735/blob/master/User_Setup.h#L7-L11):
#define TAB_COLOUR INITR_GREENTAB
option instead of
#define TAB_COLOUR INITR_GREENTAB2

**Comment by McNugget6750** [comment]
Thanks a lot! I tested all and 
`#define TAB_COLOUR INITR_BLACKTAB`
seems to have done the trick.

**Comment by Bodmer** [comment]
Gret, thanks for letting me know.
