### ISSUE TITLE
Question: Reading pixels should allow sliding graphs or sliding images?!

### ISSUE THREAD

**Issue by McNugget6750** [Bodmer/TFT_ST7735#18]
Hi there,

I am using your library because it's really really fast in comparison. But since it's so fast, I started wondering if there is a way to create sliding graphs without a large frame buffer on an Arduino Nano.
I think the answer would be to read back the pixels that need to be moved and write them back into the display immediately after.
That's a bit like writing the last displayed graph again in background color to clear it and then draw a new graph with an offset. However, maybe reading and writing and just adding one value would be faster and more efficient?
Any ideas / comments?

**Comment by Bodmer** [comment]
The Arduino Nano does not have the processing power to make the scrolling of a large arbitrary area fast enough to be visually acceptable. The MCUFRIEND_KBV library has a test sketch that uses the hardware scroll facility built into displays and software scrollling of a small area. See[ video here ](https://www.youtube.com/watch?v=Js4wykWY6zg)at around 2:55 in.

The way I have handled graphs is to draw over the old one erasing pixel by pixel.
