### ISSUE TITLE
BL pin and 128x128

### ISSUE THREAD

**Issue by eried** [Bodmer/TFT_ST7735#8]
Thanks for the library! 

What is the BL pin used for? just leave it unplugged?

Has anyone tried this library with the "Mickey mouse" one (128x128) from eBay? (I am going to try soon, but it would be nice if someone knows something)

**Comment by Bodmer** [comment]
The BL pin is probably for the backlight LEDs that illuminate the display. Usually the line should be connected to VCC.

Some displays have an onboard regulator (visible on the PCB of the displays I have) that accepts 5V, others must be powered from 3.3V.

**Comment by eried** [comment]
OK. At the end BL was not needed for the LCD with Mickey: https://www.ebay.com/itm/1-44-128x128-65K-SPI-Full-Color-TFT-LCD-Display-Module-ST7735-OLED-for-Arduino/173320874733
