### ISSUE TITLE
Request support for ST7789 in the Arduino library for a 240x240 1.3” OLED display

### ISSUE THREAD

**Issue by JOHugo** [Bodmer/TFT_ST7735#9]
Hi. I’ve got a new 240x240 LCD with a ST7789 chip on it and would like to use it with an Arduino.

I see Adafruit added support for the ST7789 in their Arduino ST7735-Library and you added it to your TFT_eSPI library. 

Are there any plans to add support for the ST7789 in the Arduino ST7735 library as well ?

**Comment by Bodmer** [comment]
I have migrated my projects to the ESP8266 and ESP32 so other than bug fixes I do mot have time available to advance this library.
